SET(CLIPBOARD_SEARCH_PATHS
	${CMAKE_CURRENT_SOURCE_DIR}/lib
)

FIND_PATH(CLIPBOARD_INCLUDE_DIR clipboard/libclipboard.h
	HINTS
	$ENV{CLIPBOARDDIR}
	PATH_SUFFIXES /include
	PATHS ${CLIPBOARD_SEARCH_PATHS}
)

FIND_LIBRARY(CLIPBOARD_LIBRARY
	NAMES clipboard
	HINTS
	PATH_SUFFIXES /lib
	PATHS ${CLIPBOARD_SEARCH_PATHS}
)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(CLIPBOARD REQUIRED_VARS CLIPBOARD_LIBRARY CLIPBOARD_INCLUDE_DIR)

